name: Scrape

on:
  push:
    paths:
      - .github/workflows/scrape.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://cwfis.cfs.nrcan.gc.ca/geoserver/public/wfs?SERVICE=WFS&REQUEST=GetFeature&OUTPUTFORMAT=application/json&TYPENAME=public:activefires_current
          downloaded_filename: data/fires-${{ steps.date.outputs.date }}.json
          postprocess: postprocess.js
