name: Scrape

on:
  push:
    paths:
      - .github/workflows/scrape.yml
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install packages
        run: npm i node-fetch mapshaper
      - name: Download and parse data
        run: node data.mjs
      - name: Commit data
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add src/data/*
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
